kind: pipeline
type: docker
name: resuelve

steps:
- name: test
  image: node:10.20.1-alpine3.11
  commands: 
  - npm install
  - npm run test

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token

- name: publishg
  image: plugins/docker
  settings:
    username: docker_username
    password: docker_password
    repo: docker.io/vickpalomo/resuelve
    tags: latest
    debug: true
